server {
    listen 443 ssl;
    server_name __DOMAIN__;

    ssl_certificate     /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;

    # Pilot 2 loads this page from the "Open Platforms" URL.
    location = /login {
        default_type text/html;
        alias /usr/share/nginx/html/login.html;
    }
    location = / {
        default_type text/html;
        alias /usr/share/nginx/html/login.html;
    }
}
